server.port=7999
spring.application.name=video-service


# Register with central DiscoveryServer on port 8000
eureka.client.service-url.defaultZone=http://localhost:8000/eureka/
eureka.instance.prefer-ip-address=true