spring.application.name=Auth-Service

server.port=8020

# Connect API Gateway to Eureka Discovery Server
eureka.client.service-url.defaultZone=http://localhost:8000/eureka/
eureka.instance.prefer-ip-address=true

#spring.datasource.url=jdbc:postgresql://localhost:5432/hireflowAuth
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://ep-broad-snow-a1axd5yx-pooler.ap-southeast-1.aws.neon.tech/hireflow-authDb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wM5BZGuANa0p
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
