spring.application.name=DiscoveryServer
server.port=8000

# Eureka specific configs
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Override default peer URL so it doesn't use 8761
eureka.client.service-url.defaultZone=http://localhost:${server.port}/eureka/